import * as vscode from "vscode";
import { OverlayRecord, OverlayStore } from "./overlayStore";
import { basename, dirname, isDependency, isDescendant, isHidden, join, normalize } from "./paths";

export const SCHEME = "todo";

interface FileEntry {
  type: vscode.FileType.File;
  ctime: number;
  mtime: number;
  data: Uint8Array;
}

interface DirectoryEntry {
  type: vscode.FileType.Directory;
  ctime: number;
  mtime: number;
}

type Entry = FileEntry | DirectoryEntry;

export type ChangeKind = "modified" | "added" | "deleted";

export interface FileChange {
  path: string;
  kind: ChangeKind;
}

function equalBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.byteLength !== b.byteLength) return false;
  for (let i = 0; i < a.byteLength; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

/** The seeded workspace generated by `ide/build.mjs`. */
export interface WorkspaceManifest {
  version: string;
  files: Record<string, string>;
}

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/**
 * An in-memory file system seeded from the exercise sources, with the
 * candidate's changes persisted to IndexedDB.
 */
export class WorkspaceFileSystem implements vscode.FileSystemProvider {
  private readonly entries = new Map<string, Entry>();
  /** The seeded content of each file, i.e. the exercise as the candidate received it. */
  private readonly original = new Map<string, Uint8Array>();
  private readonly changeEmitter = new vscode.EventEmitter<vscode.FileChangeEvent[]>();
  readonly onDidChangeFile = this.changeEmitter.event;

  /** Resolves once the seeded files and persisted changes are loaded. */
  readonly ready: Promise<void>;

  constructor(
    /** The URI of the project root, e.g. `todo:/example-todo-app` */
    readonly root: vscode.Uri,
    private readonly store: OverlayStore,
    manifestUrl: string,
  ) {
    this.ready = this.load(manifestUrl);
  }

  private async load(manifestUrl: string): Promise<void> {
    const response = await fetch(manifestUrl);
    if (!response.ok) {
      throw new Error(`Failed to load workspace: ${response.status} ${response.statusText}`);
    }
    const manifest: WorkspaceManifest = await response.json();
    const now = Date.now();
    this.entries.set("", { type: vscode.FileType.Directory, ctime: now, mtime: now });
    for (const [path, content] of Object.entries(manifest.files)) {
      const data = encoder.encode(content);
      this.original.set(path, data);
      this.setFile(path, data, now, now);
    }

    // Changes made against an older version of the exercise no longer apply
    const version = await this.store.getMeta<string>("version");
    if (version !== manifest.version) {
      await this.store.clear();
      await this.store.setMeta("version", manifest.version);
      return;
    }
    const records = await this.store.getAll();
    records.sort((a, b) => a.path.split("/").length - b.path.split("/").length);
    for (const record of records) {
      if (record.kind === "deleted") {
        this.removeTree(record.path);
      } else if (record.kind === "dir") {
        this.ensureDirectory(record.path, record.ctime);
      } else if (record.data) {
        this.setFile(record.path, record.data, record.ctime, record.mtime);
      }
    }
  }

  /** Discards all of the candidate's changes. Takes effect on the next load. */
  async reset(): Promise<void> {
    await this.store.clear();
  }

  // --- Synchronous helpers used by the bundler and search providers ---

  toPath(uri: vscode.Uri): string {
    const rootPath = this.root.path.replace(/\/+$/, "");
    // TypeScript resolves directory imports like `import "./"` with a trailing slash
    const path = uri.path.replace(/\/+$/, "");
    if (path === rootPath) return "";
    if (path.startsWith(rootPath + "/")) return normalize(path.slice(rootPath.length + 1));
    // Anything above the project root is treated as the root itself
    return rootPath.startsWith(path) ? "" : normalize(path);
  }

  toUri(path: string): vscode.Uri {
    return path === "" ? this.root : vscode.Uri.joinPath(this.root, path);
  }

  isFile(path: string): boolean {
    return this.entries.get(path)?.type === vscode.FileType.File;
  }

  isDirectory(path: string): boolean {
    return this.entries.get(path)?.type === vscode.FileType.Directory;
  }

  readSync(path: string): Uint8Array | undefined {
    const entry = this.entries.get(path);
    return entry?.type === vscode.FileType.File ? entry.data : undefined;
  }

  readTextSync(path: string): string | undefined {
    const data = this.readSync(path);
    return data && decoder.decode(data);
  }

  originalSync(path: string): Uint8Array | undefined {
    return this.original.get(path);
  }

  /** Visible files that differ from the original exercise, like `git status`. */
  changes(): FileChange[] {
    const changes: FileChange[] = [];
    for (const path of this.visibleFiles()) {
      const original = this.original.get(path);
      if (!original) changes.push({ path, kind: "added" });
      else if (!equalBytes(original, this.readSync(path)!)) changes.push({ path, kind: "modified" });
    }
    for (const path of this.original.keys()) {
      if (!isHidden(path) && !this.isFile(path)) changes.push({ path, kind: "deleted" });
    }
    return changes.sort((a, b) => a.path.localeCompare(b.path));
  }

  /** All files the candidate can see, i.e. excluding dependencies and tooling config. */
  visibleFiles(): string[] {
    return [...this.entries.entries()]
      .filter(([path, entry]) => entry.type === vscode.FileType.File && !isHidden(path))
      .map(([path]) => path)
      .sort();
  }

  // --- FileSystemProvider ---

  watch(): vscode.Disposable {
    // All changes go through this provider, so they're already reported
    return new vscode.Disposable(() => undefined);
  }

  async stat(uri: vscode.Uri): Promise<vscode.FileStat> {
    await this.ready;
    const path = this.toPath(uri);
    const entry = this.lookup(uri, path);
    return {
      type: entry.type,
      ctime: entry.ctime,
      mtime: entry.mtime,
      size: entry.type === vscode.FileType.File ? entry.data.byteLength : 0,
      permissions: isDependency(path) ? vscode.FilePermission.Readonly : undefined,
    };
  }

  async readDirectory(uri: vscode.Uri): Promise<[string, vscode.FileType][]> {
    await this.ready;
    const path = this.toPath(uri);
    const entry = this.lookup(uri, path);
    if (entry.type !== vscode.FileType.Directory) throw vscode.FileSystemError.FileNotADirectory(uri);
    const result: [string, vscode.FileType][] = [];
    for (const [childPath, child] of this.entries) {
      if (childPath !== "" && dirname(childPath) === path) {
        result.push([basename(childPath), child.type]);
      }
    }
    return result;
  }

  async readFile(uri: vscode.Uri): Promise<Uint8Array> {
    await this.ready;
    const entry = this.lookup(uri, this.toPath(uri));
    if (entry.type !== vscode.FileType.File) throw vscode.FileSystemError.FileIsADirectory(uri);
    return entry.data;
  }

  async createDirectory(uri: vscode.Uri): Promise<void> {
    await this.ready;
    const path = this.toPath(uri);
    this.assertWritable(uri, path);
    if (this.entries.has(path)) throw vscode.FileSystemError.FileExists(uri);
    this.assertParentDirectory(uri, path);
    const now = Date.now();
    this.entries.set(path, { type: vscode.FileType.Directory, ctime: now, mtime: now });
    await this.store.put([{ path, kind: "dir", ctime: now, mtime: now }]);
    this.fire({ type: vscode.FileChangeType.Created, uri });
  }

  async writeFile(
    uri: vscode.Uri,
    content: Uint8Array,
    options: { create: boolean; overwrite: boolean },
  ): Promise<void> {
    await this.ready;
    const path = this.toPath(uri);
    this.assertWritable(uri, path);
    const existing = this.entries.get(path);
    if (existing?.type === vscode.FileType.Directory) throw vscode.FileSystemError.FileIsADirectory(uri);
    if (!existing && !options.create) throw vscode.FileSystemError.FileNotFound(uri);
    if (existing && options.create && !options.overwrite) throw vscode.FileSystemError.FileExists(uri);
    this.assertParentDirectory(uri, path);

    const now = Date.now();
    const ctime = existing?.ctime ?? now;
    const data = new Uint8Array(content);
    this.entries.set(path, { type: vscode.FileType.File, ctime, mtime: now, data });
    await this.store.put([{ path, kind: "file", data, ctime, mtime: now }]);
    this.fire({ type: existing ? vscode.FileChangeType.Changed : vscode.FileChangeType.Created, uri });
  }

  async delete(uri: vscode.Uri, options: { recursive: boolean }): Promise<void> {
    await this.ready;
    const path = this.toPath(uri);
    this.assertWritable(uri, path);
    this.lookup(uri, path);
    const children = [...this.entries.keys()].filter((p) => isDescendant(p, path));
    if (children.length > 0 && !options.recursive) throw vscode.FileSystemError.NoPermissions(uri);
    const removed = this.removeTree(path);
    await this.store.put(removed.map((p) => this.tombstone(p)));
    this.fire({ type: vscode.FileChangeType.Deleted, uri });
  }

  async rename(oldUri: vscode.Uri, newUri: vscode.Uri, options: { overwrite: boolean }): Promise<void> {
    await this.ready;
    const oldPath = this.toPath(oldUri);
    const newPath = this.toPath(newUri);
    this.assertWritable(oldUri, oldPath);
    this.assertWritable(newUri, newPath);
    this.lookup(oldUri, oldPath);
    if (this.entries.has(newPath) && !options.overwrite) throw vscode.FileSystemError.FileExists(newUri);
    this.assertParentDirectory(newUri, newPath);

    const records: OverlayRecord[] = this.removeTree(newPath).map((p) => this.tombstone(p));
    const moved = [...this.entries.entries()].filter(([p]) => p === oldPath || isDescendant(p, oldPath));
    for (const [p] of moved) {
      this.entries.delete(p);
      records.push(this.tombstone(p));
    }
    const now = Date.now();
    for (const [p, entry] of moved) {
      const target = newPath + p.slice(oldPath.length);
      const updated = { ...entry, mtime: now };
      this.entries.set(target, updated);
      records.push(
        updated.type === vscode.FileType.File
          ? { path: target, kind: "file", data: updated.data, ctime: updated.ctime, mtime: now }
          : { path: target, kind: "dir", ctime: updated.ctime, mtime: now },
      );
    }
    await this.store.put(records);
    this.fire(
      { type: vscode.FileChangeType.Deleted, uri: oldUri },
      { type: vscode.FileChangeType.Created, uri: newUri },
    );
  }

  // --- Internals ---

  private lookup(uri: vscode.Uri, path: string): Entry {
    const entry = this.entries.get(path);
    if (!entry) throw vscode.FileSystemError.FileNotFound(uri);
    return entry;
  }

  private assertWritable(uri: vscode.Uri, path: string): void {
    if (path === "" || isDependency(path)) throw vscode.FileSystemError.NoPermissions(uri);
  }

  private assertParentDirectory(uri: vscode.Uri, path: string): void {
    const parent = this.entries.get(dirname(path));
    if (!parent) throw vscode.FileSystemError.FileNotFound(uri.with({ path: dirname(uri.path) }));
    if (parent.type !== vscode.FileType.Directory) throw vscode.FileSystemError.FileNotADirectory(uri);
  }

  private setFile(path: string, data: Uint8Array, ctime: number, mtime: number): void {
    this.ensureDirectory(dirname(path), ctime);
    this.entries.set(path, { type: vscode.FileType.File, ctime, mtime, data });
  }

  private ensureDirectory(path: string, time: number): void {
    const segments = path.split("/").filter(Boolean);
    for (let i = 1; i <= segments.length; i++) {
      const dir = join(...segments.slice(0, i));
      if (!this.entries.has(dir)) {
        this.entries.set(dir, { type: vscode.FileType.Directory, ctime: time, mtime: time });
      }
    }
  }

  /** Removes a path and everything below it, returning the removed paths. */
  private removeTree(path: string): string[] {
    const removed = [...this.entries.keys()].filter((p) => p === path || isDescendant(p, path));
    for (const p of removed) this.entries.delete(p);
    return removed;
  }

  private tombstone(path: string): OverlayRecord {
    const now = Date.now();
    return { path, kind: "deleted", ctime: now, mtime: now };
  }

  private fire(...events: vscode.FileChangeEvent[]): void {
    this.changeEmitter.fire(events);
  }
}
